### ISSUE TITLE
Support vim-like keybinding for navigation

### ISSUE THREAD

**Issue by goetzc** [yory8/clipman#19]
Having Vim-like keybindings would be handy, for not having to leave the home row.

Like pressing `Ctrl-j` to go down and `Ctrl-k` to go up.

**Comment by yory8** [comment]
For the gui, we rely on third party tools: either dmenu or rofi. It's up to them to implement keybindings!

**Comment by yory8** [comment]
(btw, it should be very easy to patch dmenu up with home-row support, being a suckless tool it's actually *meant* for such customization

**Comment by goetzc** [comment]
Thanks @yory8. Is there a way to have the clipboard content send to stdout, and the selection to be read from stdin? 

This way it could be feed to fzf (as it supports [many navigation forms](https://github.com/junegunn/fzf#using-the-finder)) and then back to clipman for the selection to be stored on the clipboard?

**Comment by yory8** [comment]
No, the design doesn't allow it.
However, the demon and the selector are independent. 
You could use clipman only as a demon, then whip up your own unix pipe. Every time the demon updates history, it dumps it on disk (~/.local/share/clipman.json; configurable) so that third-parties are free to read it (NOT write it).
