### ISSUE TITLE
Decouple index of items from actual content

### ISSUE THREAD

**Issue by yory8** [yory8/clipman#29]
Important for #22 and #27 

Problems: 

- how do we choose the filepath? Maybe: if histfile is ~/.local/share/clipman.json, then the contents are stored inside ~/.local/share/clipman_contents.json.
- what goes in the index? it must be the "label" clipped at MAXCHARS that will be showed in the selector. But this way, it will still be huge.

**Comment by brunelli** [comment]
> how do we choose the filepath?

IIRC clipmenu uses a histdir (instead of histfile) and will save the clipboard content as a file named after the content's hash. E.g. "test" would be saved in `$histdir/a94a8fe5ccb19ba61c4c0873d391e987982fbbd3` and a line would be appended to the `$histdir/clipmenu.linecache` file with the hash (a94a8fe5ccb19ba61c4c0873d391e987982fbbd3) and a preview of the content — which in this case is the whole string, but it could be clippled in case of a longer string or be something like "Image (PNG) - 1920x1080 - 1.5Mb"  for an image.

**Comment by yory8** [comment]
@brunelly this might be the best solution, though I'm not fond of having tons of small files around. However, until we actually support images, this whole issue is not of much priority (I assume that most text copies are small in practice). It will most likely be a breaking change, so I want it to be worth it, that is, enable a big feature like supporting rich text/images.

**Comment by brunelli** [comment]
> though I'm not fond of having tons of small files around

I think the hardest part (or at least the part where other tools I used failed to handle) is to verify whether the file is still needed – i.e. all files that aren't in the history (maybe kept around because somehow it was deleted only in the dictionary) should be deleted – so we don't keep useless files.

> enable a big feature like supporting rich text/images

Wouldn't this come for free? AFAIK if the user has `xdg-utils` installed, `wl-copy` can infer the file's content type.

And now a new benefit comes to mind: there'd be no clipboard "leakage" anymore (right now a proccess like `wl-copy -- clipboard content` is left running) as we would pass a file directly to `wl-copy`.

**Comment by yory8** [comment]
>  is to verify whether the file is still needed

That's weird to hear, I don't see why it should be... when I delete an entry from the index I can also delete the file it references

> Wouldn't this come for free?

Yes and no. For images, yes, I could actually already implement it, but rich text requires crafting a multi-type item (for falling back to plain text if we copy in a tool that doesn't support rich text, like a terminal), and that cannot be done through wl-copy, I should use wayland directly, but it's very complex.

>  there'd be no clipboard "leakage" anymore

No, it doesn't work like that. Basically, when the application from which you copy exits (in this case, wl-copy), the clipboard is cleared; this means that wl-copy must be alive for as long as we might need to paste it's content, that is forever.

**Comment by brunelli** [comment]
> when I delete an entry from the index I can also delete the file it references

Yeah... I don't know why but it was very common in both GPaste and clipmenu.

> that cannot be done through wl-copy, I should use wayland directly, but it's very complex

Hmm... I just read the related wl-clipboard issue and that is more complex than I thought.

> No, it doesn't work like that

Sorry, I was not very clear. I'm just saying that right now if I run `ps aux | grep wl-copy` I would have an output like:

```
user        15107  0.0  0.0   2628   164 ?        S    16:22   0:00 wl-copy -- my clipboard content
user        15115  0.0  0.0   6324  2356 pts/0    S+   16:22   0:00 grep --color=auto wl-copy
```

If we used files, the `my clipboard content` part would not be there.

**Comment by yory8** [comment]
> If we used files, the my clipboard content part would not be there.

Got it now. Actually, this can already be fixed, and I have a quick patch ready. A question: we can either have it appear as `/usr/bin/wl-copy` (or wherever you have it installed), or just `wl-copy`; what's best?

**Comment by brunelli** [comment]
> EDIT: pushed to master!

I can't build current master:

```
clipman:master ➜ go install
# github.com/yory8/clipman
./main.go:115:22: serveTxt(history[len(history) - 2]) used as value
[2]
```

> I think I just found a way to do it through a gtk api

That's great!

**Comment by yory8** [comment]
Sorry, now it works. It's vscode, if you close it with unsaved stuff it doesn't warn you, it just keeps it for next time you open it.

About the gtk api, unfortunately we can't use it through go (or even python) bindings, see #22

**Comment by brunelli** [comment]
Just tested it. Really nice!

> About the gtk api, unfortunately we can't use it through go (or even python) bindings

That sucks :/

But maybe is better to don't rely on Gtk.

**Comment by yory8** [comment]
Closing as tracked in #22
