### ISSUE TITLE
yanking in neovim sometimes fails

### ISSUE THREAD

**Issue by hissssst** [yory8/clipman#50]
In my `.config/sway/config`
`exec wl-paste -p -t text --watch clipman store --notify`

Sometimes when I yank and paste data from neovim, it pastes the previous copy in previous window.

```
$ clipman -v
1.5.2
```

**Comment by yory8** [comment]
I use neovim too but never triggered this issue. Could you find whether it's random or there are some steps to reproduce?

**Comment by hissssst** [comment]
By the way, I've set `set clipboard+=unnamedplus`
I'll try to work with `-P` flag and look for steps to reproduce in next few days

**Comment by hissssst** [comment]
`clipman store -P` still fails, it happens randomly and I can't define the pattern...

**Comment by yory8** [comment]
could you clarify what "it pastes the previous copy in previous window" means? is it: I copy from, say, firefox, then I copy from neovim, then I paste and rather than the copy from neovim i get the one from firefox?

If it's so, than I wonder whether it's actually neovim than isn't really yanking for some reason. Could you see if it happens even without clipman running?

**Comment by hissssst** [comment]
@yory8 I'm in a process of defining a pattern. I've found out that this issue happens not only in neovim. 
I think I've almost found out when it happens, it's somewhere with window switching
Give me some more time. I can also provide any system and versions info, just tell me which one ;3
