### ISSUE TITLE
Don't store passwords

### ISSUE THREAD

**Issue by tigerjack** [yory8/clipman#52]
Well, the title says pretty much everything. At the moment, when I copy a password from KeePassXC, it is stored in clipman.
After pasting the password, I think KeePassXC sends something like a "clear password" signal because the password is removed from the clipboard (meaning I can't paste it anymore anywhere). So I guess that maybe there should be a way to listen for changes/deletion to the main clipboard.

**Comment by yory8** [comment]
Unfortunately not. We don't know why the clipboard has been emptied (it's also emptied when you close the application from which you last copied).
However, you can do a workaround on your own system by wrapping both the keepass and clipman binary calls with some simple shell script: before launching keepass, create a file `/tmp/clipman_ignore`. Before launching `clipman store` from wl-paste check if the file exists: if it exists, delete it and exit without calling clipman, otherwise delete it as well but launch clipman too.

**Comment by trobjo** [comment]
I just delete the password from the history after 15 seconds. That is good enough for me, but of course not viable if you turn off your computer shortly after copying a password.

```

deleter() {
    local pw="$(wl-paste -n)"
    sleep 15
    clipman clear --tool=CUSTOM --print0 --tool-args="printf \"$pw\""
}

fzf-password() {
    pass clip --fzf
    zle reset-prompt
    (deleter &) > /dev/null 2>&1
}
zle -N fzf-password
bindkey -e '^K' fzf-password
```

**Comment by yory8** [comment]
@trobjo isn't the workaround in my previous comment better? clipman will never even *store* your password if you do it like that

**Comment by bhepple** [comment]
This is easy to accomplish with sway (and probably i3wm, although I haven't used that for a long time).

Just use the following bash scriptlet - it wraps clipman, nothing to be done with keepassxc. It simply avoids all copy operations from keypassxc so even if you don't use --no-persist, you're still secure.

Don't know about Gnome/KDE though.

```
#!/usr/bin/env bash

# run this in sway as:
# exec wl-paste -t text --watch myclipman

app_id=$( swaymsg -t get_tree | jq -r '.. | select(.type?) | select(.focused==true)|.app_id'  )
if [[ $app_id != "org.keepassxc.KeePassXC" ]]; then
    clipman store --no-persist
fi
```

**Comment by Moini** [comment]
Couldn't this be built into clipman? Add a list of applications that you do not want it to work for?

**Comment by yory8** [comment]
@Moini  we can't. The clipboard doesn't know anything about the application it gets the stuff from. As for bhepple's workaround, it only works for sway, but clipman supports all wlroots-based window managers.

**Comment by Moini** [comment]
@yory8 Because of this issue, I have since switched to clipit (even though I actually like clipman's interface, its image copying functionality, and that it allows one to choose the paste shortcut more). 
Clipit provides an option to choose which app to allow copying from (at least for myself, on Xfce/Linux Mint). It seems to read the window title? Not sure.

So it would not be possible to copy that functionality from clipit?

**Comment by yory8** [comment]
AFAIK xfce is still stuck on Xorg. That's why clipit can do it. X made this stuff much easier (at the expense of security). On wayland, we are restricted from accessing other applications' data. There were talks about improving wayland's support for clipboard managers, but i think they've stalled for lack of interest.

**Comment by Moini** [comment]
Ah, I was afraid that this could be the answer. Thank you, @yory8 !

**Comment by Moini** [comment]
Btw.... do you know where one would need to knock the door, if one wanted to politely let Wayland devs know that this is useful functionality?

**Comment by yory8** [comment]
https://wayland.freedesktop.org/
either on the mailing list or on irc.

however, I don't think this particular function can ever be supported, as it goes against the secure sandbox design.
