### ISSUE TITLE
clipman does not work with some wl-copy inputs

### ISSUE THREAD

**Issue by w0land** [yory8/clipman#6]
clipman produces an error: `No suitable type of content copied` when wl-copy is triggered from NeoVim (or Vim) or from `echo evil123 | wl-copy`
This is due to invoking wl-paste with
`wl-paste -n -t text`

A quick fix is to skip `-t text` and remove trailing \n char (I have a patch prepared, but wanted author opinion on this)

**Comment by yory8** [comment]
I can't reproduce, but feel free to send the patch, thank'you

**Comment by w0land** [comment]
Awesome, thanks!

**Comment by yory8** [comment]
I reverted this fix because it breaks clipman when copying non-text data.

The issue here is actually either in neovim or wl-clipboard: either wl-clipboard should support "-t text" in wl-copy (now it only supports it in wl-paste) or neovim should use "-t TEXT". The relevant code in wl-clipboard is line 622 of `src/boilerplate.c`.
