### ISSUE TITLE
dmenu hardcoded options

### ISSUE THREAD

**Issue by mistersmee** [yory8/clipman#84]
dmenu has harcoded options in `selector.go`, to open dmenu at the bottom, and to use specific font. As far as I can tell, no other selector spawns at the bottom, or specifies a specific font. Can you please explain the reasoning behind this, as I tested removing both of those options, and it worked perfectly. 
Also, using the dmenu `-p` option, I was able to set the default prompt too.

**Comment by yory8** [comment]
I don't remember, probably was the configuration I used back then. Either way, dmenu is an obsolete application for X. I put there because at the time there wasn't a mature Wayland option yet. 

Now there's plenty, so I recommend abandoning dmenu. I keep it in the code only to avoid breaking existing configurations. 

In fact, I recommend using the custom selector rather than the hardcoded ones (on X it was pretty much just dmenu or rofi; I didn't expect so many alternatives to appear on Wayland).
