### ISSUE TITLE
Thunar Must Perform Copy/Cut Operation Twice to Successfully Execute

### ISSUE THREAD

**Issue by WammKD** [yory8/clipman#86]
When trying to copy/cut files with Thunar, the operation must be performed twice to be able to have this work.

If you only do it once, Thunar alerts that "There is nothing on the clipboard to paste." I thought, at first, that this was due to [wl-clipboard](https://github.com/bugaevc/wl-clipboard) but someone else had the same thought and, overlooking the logs, it was concluded that it seemed Clipman might be causing the issue: https://github.com/bugaevc/wl-clipboard/issues/112.

**Comment by yory8** [comment]
About the issue with thunar, I'm not sure what this is about, as the clipboard should have nothing to do with copying files.

However the issue experienced by @Iss-in (copying images in firefox) is already known. It happens because clipman doesn't support images, but when you copy an image in firefox you also get text as an option; so clipman gets the text the first time, destroying the image in the process; the second time you copy it, the text is already in memory, so clipman ignores the clipboard, leaving it whole for other applications to read.
The only way to somewhat fix this would be to ignore the clipboard whenever it's not pure text. But this would involve completely rethinking the design, as the text arrives to clipman already filtered as we call clipman from `wl-paste -t text`.

**Comment by yory8** [comment]
In case thunar's issue has the same underlying cause, you might be able to fix it by wrapping the `wl-paste -t text --watch clipman` command inside a script that checks the output of `wl-paste -l` first. If the output is: 

```
text/plain;charset=utf-8
text/plain
TEXT
STRING
UTF8_STRING
```

then you can safely call clipman, otherwise abort. Beyond that, I don't think there's anything I can do without a full rewrite/breaking backwards compatibility.

**Comment by WammKD** [comment]
Ahh, O. K. Heh, I was just about to ask how that would work, with a daemon. Thanks for explaining and walking through what might be the cause, though.

**Comment by WammKD** [comment]
Do you mean `-p` (lowercase), as in having `wl-paste` use primary (not trying to be nitpicking; just making sure I understand properly)?

**Comment by yory8** [comment]
No, clipman's option to disable persistence, which is the root of most evil

**Comment by WammKD** [comment]
Ahh; gotcha. Thanks. Yep; that works. Cutting works on first go, now, with Thunar.
