### ISSUE TITLE
Rofi prompt

### ISSUE THREAD

**Issue by Rolv-Apneseth** [yory8/clipman#93]
Apologies if this has been discussed before, I couldn't find an issue about this.

So the problem I'm having is trying to run `clipman` with the following command 

```
clipman pick --tool rofi -T"-p clipboard"
```

Ideally this would set the prompt to `clipboard` but I believe in the code here, the `-p` flag for `rofi` is set once by default already, and the second `-p` is therefore ignored.

Using the custom option works perfectly fine so this is not a big issue, just thought I could mention it and the next person looking for a fix can easily find a solution:

```
clipman pick --tool=CUSTOM -T'rofi -dmenu -p "clipboard"'
```

This is only useful because in the theme I'm using, the prompt acts more like a title.

**Comment by yory8** [comment]
Thanks.  Rofi is an X11 application which runs through xwayland. I gave it special support at the beginning of this project, because there wasn't a mature wayland solution yet.  It remains there as legacy, but I'm not interested in supporting it anymore.  I recommend switching to one of the several native wayland replacements!

**Comment by Rolv-Apneseth** [comment]
Ah I see, thanks for letting me know. Is running through `xwayland` a major downside? I ask because I have a lot of `rofi` configuration and if it's possible to not have to redo those for a different program then I'd just stick with it.

**Comment by yory8** [comment]
there's a rofi [fork](https://www.reddit.com/r/swaywm/comments/i2iuu5/rofi_fork_with_wayland_support_available/) that supports wayland natively AFAIK.

in general when there's a good alternative it would be better to ditch x11-only apps, because while xwayland will probably be around for years/decades, it's just meant as a way to smooth the transition to the new standard.

**Comment by Rolv-Apneseth** [comment]
Ah nice, thanks for letting me know about that fork. Getting set up on Wayland has been quite hard honest. I'll give that fork a try, I see it's in the AUR too as `rofi-lbonn-wayland`
